version: "3.9"

services:

  backend:
    build: ./backend
    container_name: enterprise-backend
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/enterprise_ops
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      JWT_SECRET: superProductionSecretKeyChangeMe
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: enterprise-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: enterprise-db
    environment:
      POSTGRES_DB: enterprise_ops
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"